using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CloaudeAiLibrary.Models
{
    public class ParsedCvModel
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string Profession { get; set; }
        public string Summary { get; set; }
        public List<string> JobTitles { get; set; } = new();
        public List<string> Skills { get; set; } = new();
        public int? ExperienceYears { get; set; }
        public string Education { get; set; }
        public string MilitaryService { get; set; }
        public string Languages { get; set; }

        // Generated by Claude — used for Qdrant embedding
        public string EnrichedText { get; set; }
    }
}
